"""Explicit allowlists exclude future prices and targets from model inputs."""

move_features = [
    "volatility_1h",
    "volatility_2h",
    "volatility_4h",
    "range",
    "body",
    "return_5m",
    "return_15m",
    "return_30m",
    "MA20_slope",
    "MA50_slope",
    "distance_high_1h",
    "distance_low_1h",
    "hour_sin",
    "hour_cos",
    "weekday",
]

direction_features = [
    "return_5m",
    "return_15m",
    "return_30m",
    "return_1h",
    "return_2h",
    "MA5_distance",
    "MA20_distance",
    "MA50_distance",
    "MA5_slope",
    "MA20_slope",
    "MA50_slope",
    "RSI",
    "bullish",
    "body",
    "upper_wick",
    "lower_wick",
    "distance_high_1h",
    "distance_low_1h",
    "volatility_1h",
    "hour_sin",
    "hour_cos",
    "weekday",
]

quality_market_features = [
    "return_5m",
    "return_15m",
    "return_30m",
    "return_1h",
    "return_2h",
    "volatility_1h",
    "volatility_2h",
    "volatility_4h",
    "ATR14_pct",
    "ADX14",
    "RSI",
    "MA5_distance",
    "MA20_distance",
    "MA50_distance",
    "MA5_slope",
    "MA20_slope",
    "MA50_slope",
    "distance_high_1h",
    "distance_low_1h",
    "body",
    "range",
    "upper_wick",
    "lower_wick",
    "hour_sin",
    "hour_cos",
    "weekday",
]
